"""add material_ids columns

Revision ID: 1375c49fce79
Revises: 0ab558424651
Create Date: 2025-02-07 13:49:54.883950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1375c49fce79'
down_revision: Union[str, None] = '0ab558424651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('material_ids', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'material_ids')
    # ### end Alembic commands ###
